
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xotlbupzkhhgiiogjeks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdGxidXB6a2hoZ2lpb2dqZWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODY1NzQsImV4cCI6MjA1NzU2MjU3NH0.kBk6k9IfGUu94qlsE8osBbYAP2aHBZ4KQETcKkJVpO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
